apiVersion: v1
kind: Service
metadata:
  name: aradin-converter-svc
  namespace: aradin
  labels:
    app: aradin-converter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
spec:
  type: NodePort
  selector:
    app: aradin-converter
  ports:
    - name: http
      port: 5000
      targetPort: http
      nodePort: 30080
      protocol: TCP
